name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    container:
      image: ghcr.io/armmbed/mbed-os-env:master-latest
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    strategy:
      matrix:
        target: [LEXXPLUSS_PB01]
        profile: [release]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        id: build
        run: |
          set -e
          mbed-tools deploy
          mbed-tools compile -t GCC_ARM -m ${{ matrix.target }} --profile ${{ matrix.profile }}
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#div-02-robotics-ci'
        if: always()
